import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { IoCloseOutline, IoVolumeHighOutline, IoVolumeMuteOutline } from 'react-icons/io5';
import { useAudio } from '../hooks/useAudio';
import { useBreakScheduler } from '../hooks/useBreakScheduler';

/**
 * Serenity Break Modal - guided meditation with ElevenLabs audio
 * TODO: Connect to backend /breaks/meditation endpoint to get audio URL
 */
const SerenityBreak = ({ onClose }) => {
  const [breakPhase, setBreakPhase] = useState('intro'); // intro, meditation, complete
  const [timeRemaining, setTimeRemaining] = useState(300); // 5 minutes in seconds
  const { audioRef, isPlaying, play, pause, volume, setVolume } = useAudio();
  const { upcomingBreak, startBreak, completeBreak } = useBreakScheduler();

  useEffect(() => {
    // TODO: API Call - Fetch meditation audio from backend
    // const audioUrl = await fetchMeditationAudio(upcomingBreak?.id);
    // loadAudio(audioUrl);
    
    // Mock audio URL for development
    // In production, this would be generated by ElevenLabs via backend
    console.log('Loading meditation audio from ElevenLabs...');
  }, []);

  useEffect(() => {
    if (breakPhase === 'meditation' && timeRemaining > 0) {
      const timer = setInterval(() => {
        setTimeRemaining(prev => {
          if (prev <= 1) {
            setBreakPhase('complete');
            pause();
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
      return () => clearInterval(timer);
    }
  }, [breakPhase, timeRemaining]);

  const handleStartBreak = async () => {
    setBreakPhase('meditation');
    await play();
    if (upcomingBreak) {
      startBreak(upcomingBreak.id);
    }
  };

  const handleCompleteBreak = async () => {
    if (upcomingBreak) {
      await completeBreak(upcomingBreak.id, {
        duration: 300 - timeRemaining,
        completed: true,
      });
    }
    onClose();
  };

  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-ocean-900/50 backdrop-blur-sm">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.9 }}
          className="relative w-full max-w-2xl glass-card p-8 overflow-hidden"
        >
          {/* Close button */}
          <button
            onClick={onClose}
            className="absolute top-4 right-4 p-2 text-ocean-600 hover:text-ocean-800 hover:bg-ocean-50 rounded-full transition-colors z-10"
          >
            <IoCloseOutline size={24} />
          </button>

          {/* Animated background elements */}
          <div className="absolute inset-0 overflow-hidden pointer-events-none">
            <motion.div
              animate={{
                scale: [1, 1.2, 1],
                opacity: [0.3, 0.5, 0.3],
              }}
              transition={{
                duration: 8,
                repeat: Infinity,
                ease: 'easeInOut',
              }}
              className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-ocean-300 rounded-full blur-3xl"
            ></motion.div>
          </div>

          {/* Content */}
          <div className="relative z-10">
            {breakPhase === 'intro' && (
              <IntroPhase onStart={handleStartBreak} />
            )}

            {breakPhase === 'meditation' && (
              <MeditationPhase
                timeRemaining={timeRemaining}
                formatTime={formatTime}
                isPlaying={isPlaying}
                onPlayPause={() => isPlaying ? pause() : play()}
                volume={volume}
                onVolumeChange={setVolume}
              />
            )}

            {breakPhase === 'complete' && (
              <CompletePhase onComplete={handleCompleteBreak} />
            )}
          </div>

          {/* Hidden audio element */}
          <audio ref={audioRef} className="hidden" />
        </motion.div>
      </div>
    </AnimatePresence>
  );
};

const IntroPhase = ({ onStart }) => (
  <motion.div
    initial={{ opacity: 0, y: 20 }}
    animate={{ opacity: 1, y: 0 }}
    className="text-center py-8"
  >
    <motion.div
      animate={{ scale: [1, 1.1, 1] }}
      transition={{ duration: 2, repeat: Infinity }}
      className="text-8xl mb-6"
    >
      🧘
    </motion.div>
    <h2 className="text-3xl font-bold text-ocean-800 mb-4">Time for Your Serenity Break</h2>
    <p className="text-ocean-600 mb-8 max-w-md mx-auto">
      Take a 5-minute guided meditation to reset your mind and boost productivity.
      Find a comfortable position and let the calming audio guide you.
    </p>
    <button onClick={onStart} className="btn-primary text-lg px-8 py-4">
      Begin Meditation 🌊
    </button>
  </motion.div>
);

const MeditationPhase = ({ timeRemaining, formatTime, isPlaying, onPlayPause, volume, onVolumeChange }) => (
  <motion.div
    initial={{ opacity: 0 }}
    animate={{ opacity: 1 }}
    className="text-center py-8"
  >
    {/* Breathing circle animation */}
    <div className="relative w-64 h-64 mx-auto mb-8">
      <motion.div
        animate={{
          scale: [1, 1.3, 1],
          opacity: [0.6, 0.8, 0.6],
        }}
        transition={{
          duration: 4,
          repeat: Infinity,
          ease: 'easeInOut',
        }}
        className="absolute inset-0 rounded-full ocean-gradient opacity-40"
      ></motion.div>
      <motion.div
        animate={{
          scale: [1, 1.2, 1],
          opacity: [0.8, 1, 0.8],
        }}
        transition={{
          duration: 4,
          repeat: Infinity,
          ease: 'easeInOut',
        }}
        className="absolute inset-8 rounded-full bg-serenity flex items-center justify-center"
      >
        <div className="text-center">
          <p className="text-sm text-ocean-600 mb-2">Breathe</p>
          <p className="text-4xl font-bold text-ocean-800">{formatTime(timeRemaining)}</p>
        </div>
      </motion.div>
    </div>

    {/* Instructions */}
    <motion.p
      animate={{ opacity: [0.5, 1, 0.5] }}
      transition={{ duration: 3, repeat: Infinity }}
      className="text-ocean-600 mb-8"
    >
      Breathe deeply... Let your thoughts flow like water...
    </motion.p>

    {/* Controls */}
    <div className="flex items-center justify-center space-x-6">
      <button
        onClick={onPlayPause}
        className="w-16 h-16 rounded-full ocean-gradient text-white flex items-center justify-center hover:shadow-xl transition-shadow"
      >
        {isPlaying ? '⏸' : '▶️'}
      </button>

      <div className="flex items-center space-x-3">
        <button onClick={() => onVolumeChange(volume > 0 ? 0 : 0.7)}>
          {volume > 0 ? <IoVolumeHighOutline size={24} className="text-ocean-600" /> : <IoVolumeMuteOutline size={24} className="text-ocean-600" />}
        </button>
        <input
          type="range"
          min="0"
          max="1"
          step="0.1"
          value={volume}
          onChange={(e) => onVolumeChange(parseFloat(e.target.value))}
          className="w-24 accent-ocean-500"
        />
      </div>
    </div>
  </motion.div>
);

const CompletePhase = ({ onComplete }) => (
  <motion.div
    initial={{ opacity: 0, scale: 0.9 }}
    animate={{ opacity: 1, scale: 1 }}
    className="text-center py-8"
  >
    <motion.div
      animate={{ rotate: [0, 10, -10, 0] }}
      transition={{ duration: 0.5 }}
      className="text-8xl mb-6"
    >
      ✨
    </motion.div>
    <h2 className="text-3xl font-bold text-ocean-800 mb-4">Well Done!</h2>
    <p className="text-ocean-600 mb-8 max-w-md mx-auto">
      You've completed your Serenity Break. Feel refreshed and ready to continue your productive day.
    </p>
    <button onClick={onComplete} className="btn-primary text-lg px-8 py-4">
      Return to Dashboard
    </button>
  </motion.div>
);

export default SerenityBreak;
